# Generated by Django 5.2.6 on 2025-10-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('LOW_STOCK', 'Low stock')], default='LOW_STOCK', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.material')),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'is_resolved'], name='products_al_type_9aa851_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('material', 'type', 'is_resolved'), name='uniq_open_lowstock')],
            },
        ),
    ]
