# Generated by Django 5.2.7 on 2025-11-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alert'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='materials', through='suppliers.MaterialSupplier', to='suppliers.supplier'),
        ),
    ]
